mqtt:
  enabled: False
  
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
  name_of_your_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@10.0.10.10:554/h264Preview_01_sub # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://user:pass@10.0.10.10:554/h264Preview_01_main # <----- Add stream you want to record from
          roles:
            - record
      hwaccel_args: preset-rpi-64-h264
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: False
    snapshots: # <----- Enable snapshots
      enabled: False